// ---------------------------------------------------------------------------
// fix-misread-dc — ONE-TIME cleanup of already-published picks whose market was
// MISREAD (mostly "Double Chance X/2/AWAY/DNB(2)" — a plain draw, an away win, or
// a Draw-No-Bet that the old extractor forced into a bogus Double Chance that
// then always settled LOST). Re-reads each through canonicalizePick(), relabels
// it as the REAL market, and re-settles it from the recorded final score. Frozen
// past picks aren't regenerated by the pipeline, so they need this direct pass.
// (New picks are already read correctly at ingestion — see jsonImport.)
// ---------------------------------------------------------------------------
import fs from 'node:fs';
import path from 'node:path';
import { canonicalizePick, marketLabel, settle, matchKey } from '../src/lib/aggregation/normalize.ts';
import type { MarketGroup } from '../src/lib/aggregation/types.ts';

const ROOT = process.cwd();
const TIPS = path.join(ROOT, 'src', 'content', 'tips');
const WRITE = process.argv.includes('--write');

const MARKET_NAME: Record<string, string> = {
  '1X2': 'Match Result', OU25: 'Total Goals', BTTS: 'Both Teams to Score',
  DC: 'Double Chance', DNB: 'Draw No Bet',
};
// reverse of the display name -> market code, to read a published pick back
const CODE: Record<string, MarketGroup> = {
  'match result': '1X2', 'total goals': 'OU25', 'both teams to score': 'BTTS',
  'double chance': 'DC', 'draw no bet': 'DNB', prediction: 'OTHER',
};

// real final scores
const outs = new Map<string, { hg: number; ag: number }>();
try {
  const ro = JSON.parse(fs.readFileSync(path.join(ROOT, 'src', 'data', 'real-outcomes.json'), 'utf8'));
  const arr = Array.isArray(ro) ? ro : (ro.outcomes ?? Object.values(ro));
  for (const o of arr) if (o?.matchKey) outs.set(o.matchKey, { hg: +o.hg, ag: +o.ag });
} catch {}

// Recover a raw selection token from a published pick label so canonicalizePick
// can re-read it (labels don't store the raw selection).
function selFromLabel(pick: string): string {
  return pick
    .replace(/double chance/i, '')
    .replace(/\(draw no bet\)/i, ' dnb')
    .replace(/\bwin\b/i, '')
    .replace(/goals?|\bpoints?\b/gi, '')
    .trim();
}

let scanned = 0, fixed = 0, resettled = 0;
const changes: string[] = [];
for (const f of fs.readdirSync(TIPS)) {
  if (!f.endsWith('.md')) continue;
  const p = path.join(TIPS, f);
  const orig = fs.readFileSync(p, 'utf8');
  const nl = orig.includes('\r\n') ? '\r\n' : '\n';
  const t = orig.replace(/\r\n/g, '\n');
  const fm = t.match(/^---\n([\s\S]*?)\n---/); if (!fm) continue;
  const g = (k: string) => (fm[1].match(new RegExp(`^${k}:\\s*(.*)$`, 'm'))?.[1] ?? '').trim().replace(/^"|"$/g, '');
  const marketName = g('market'); const pick = g('pick');
  const [home, away] = g('match').split(/\s+vs\s+/i);
  if (!home || !away) continue;

  // Only the broken ones: a "Double Chance <token>" whose token isn't 1X/12/X2.
  const dcTok = pick.match(/double chance\s+(.+)$/i)?.[1]?.trim().toLowerCase();
  const brokenDC = dcTok != null && !['1x', '12', 'x2'].includes(dcTok);
  if (!brokenDC) continue;
  scanned++;

  const code = CODE[marketName.toLowerCase()] ?? 'DC';
  const c = canonicalizePick(code, selFromLabel(pick), home, away);
  if (!c) { changes.push(`DROP-worthy (unreadable): ${pick} | ${home} v ${away} [${f}]`); continue; }
  const newPick = marketLabel(c.market, c.selection, home, away, c.line);
  const newMarket = MARKET_NAME[c.market] ?? 'Prediction';

  // re-settle from the real score if we have it
  let newResult = g('result');
  const o = outs.get(matchKey(home, away, g('kickoff')));
  if (o && Number.isFinite(o.hg)) { newResult = settle(c.market, c.selection, o.hg, o.ag, c.line); resettled++; }

  changes.push(`"${pick}" -> "${newPick}" [${marketName}->${newMarket}] result ${g('result')}->${newResult} | ${home} v ${away}`);
  fixed++;
  if (WRITE) {
    let out = t
      .replace(/^market:\s*.*$/m, `market: ${JSON.stringify(newMarket)}`)
      .replace(/^pick:\s*.*$/m, `pick: ${JSON.stringify(newPick)}`)
      .replace(/^result:\s*.*$/m, `result: ${newResult}`);
    fs.writeFileSync(p, out.replace(/\n/g, nl));
  }
}
console.log(`scanned broken-DC: ${scanned}, fixed: ${fixed}, re-settled: ${resettled}, mode: ${WRITE ? 'WRITE' : 'DRY'}`);
changes.forEach((x) => console.log('  ' + x));
